apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-expense-sc
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-06f099f91a00540e4 # replace with your EFS file system ID
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/expense" # optional