apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  storageClassName: "efs-expense-sc" #must be empty for dynamic provisioning otherwise dynamic provisioning will be used
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    purpose: "efs-dynamic-demo"
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1b #replace with your zone
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    purpose: "efs-dynamic-demo"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
