apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx:latest
    env:
    - name: ENVIRONMENT
      value: dev
    - name: LOG_LEVEL
      value: DEBUG  
    - name: DB_HOST
      value: mysql.expense.svc.cluster.local
    - name: DB_PORT
      value: "3306"