apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector: #nlabels are used as selectors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #pod port
---
kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
spec:
  containers:
  - name: backend
    image: nginx:latest
 

