apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector: #nlabels are used as selectors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #pod port
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-np
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
spec:
  containers:
  - name: backend
    image: nginx:latest
 

