apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: #nlabels are used as selectors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #pod port
    nodePort: 30007 #node port
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-lb
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb
spec:
  containers:
  - name: backend
    image: nginx:latest
 

